WTF_CSRF_ENABLED = True
SECRET_KEY = 'this-is-a-secret-key-and-must-be-changed-on-the-production-machine'


# Dict of AA with D forms for lowercase
aa_dict = {'G': ['Gly', 'Glycine', 'nonpolar'],
           'A': ['Ala', 'Alanine', 'nonpolar'],
           'V': ['Val', 'Valine', 'nonpolar'],
           'L': ['Leu', 'Leucine', 'nonpolar'],
           'I': ['Ile', 'Isoleucine', 'nonpolar'],
           'M': ['Met', 'Methionine', 'nonpolar'],
           'F': ['Phe', 'Phenylalanine', 'nonpolar'],
           'W': ['Trp', 'Tryptophan', 'nonpolar'],
           'P': ['Pro', 'Proline', 'nonpolar'],
           'S': ['Ser', 'Serine', 'polar'],
           'T': ['Thr', 'Threonine', 'polar'],
           'C': ['Cys', 'Cysteine', 'polar'],
           'Y': ['Tyr', 'Tyrosine', 'polar'],
           'N': ['Asn', 'Asparagine', 'polar'],
           'Q': ['Gln', 'Glutamine', 'polar'],
           'D': ['Asp', 'Aspartic acid', 'negative'],
           'E': ['Glu', 'Glutamic acid', 'negative'],
           'K': ['Lys', 'Lysine', 'positive'],
           'R': ['Arg', 'Arginine', 'positive'],
           'H': ['His', 'Histidine', 'positive'],
           'g': ['DGly', 'D-Glycine', 'nonpolar'],
           'a': ['DAla', 'D-Alanine', 'nonpolar'],
           'v': ['DVal', 'D-Valine', 'nonpolar'],
           'l': ['DLeu', 'D-Leucine', 'nonpolar'],
           'i': ['DIle', 'D-Isoleucine', 'nonpolar'],
           'm': ['DMet', 'D-Methionine', 'nonpolar'],
           'f': ['DPhe', 'D-Phenylalanine', 'nonpolar'],
           'w': ['DTrp', 'D-Tryptophan', 'nonpolar'],
           'p': ['DPro', 'D-Proline', 'nonpolar'],
           's': ['DSer', 'D-Serine', 'polar'],
           't': ['DThr', 'D-Threonine', 'polar'],
           'c': ['DCys', 'D-Cysteine', 'polar'],
           'y': ['DTyr', 'D-Tyrosine', 'polar'],
           'n': ['DAsn', 'D-Asparagine', 'polar'],
           'q': ['DGln', 'D-Glutamine', 'polar'],
           'd': ['DAsp', 'D-Aspartic acid', 'negative'],
           'e': ['DGlu', 'D-Glutamic acid', 'negative'],
           'k': ['DLys', 'D-Lysine', 'positive'],
           'r': ['DArg', 'D-Arginine', 'positive'],
           'h': ['DHis', 'D-Histidine', 'positive']}
